#!/usr/bin/env python3
"""Different-algorithm exact audit of the MOD-360 power atlas.

CRT with repeated multiplication, Floyd cycles, local valuation/order oracle,
composition tests and trial-division prime-power pushforwards. No E4 claim.
Default/--check is read-only; --write explicitly updates the certificate.
"""
from __future__ import annotations
import argparse
from collections import Counter
import csv
import hashlib
import json
from math import gcd, isqrt, lcm
from pathlib import Path
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'data' / 'power-atlas-v1'
CERT = ROOT / 'certificates' / 'power-atlas-v1.json'


def require(ok: bool, message: str) -> None:
    if not ok:
        raise RuntimeError(message)


def csv_rows(data: bytes) -> list[list[int]]:
    return [[int(x) for x in row] for row in list(csv.reader(data.decode().splitlines()))[1:]]


def modular_product_power(a: int, k: int, modulus: int) -> int:
    b = 1
    for _ in range(k):
        b = b*a % modulus
    return b


def crt_power(a: int, k: int) -> int:
    return sum(weight * modular_product_power(a, k, modulus)
               for modulus, weight in ((8, 225), (9, 280), (5, 216))) % 360


def floyd(f: list[int], a: int) -> list[int]:
    slow, fast = f[a], f[f[a]]
    while slow != fast:
        slow, fast = f[slow], f[f[fast]]
    mu, slow = 0, a
    while slow != fast:
        slow, fast, mu = f[slow], f[fast], mu+1
    entry, period, fast = slow, 1, f[slow]
    while fast != slow:
        fast, period = f[fast], period+1
    cycle = [entry]
    for _ in range(period-1):
        cycle.append(f[cycle[-1]])
    return [a, mu, period, entry, min(cycle)]


def order(a: int, modulus: int) -> int:
    if modulus == 1:
        return 1
    require(gcd(a, modulus) == 1, 'nonunit order')
    x, d = a % modulus, 1
    while x != 1:
        x, d = x*a % modulus, d+1
    return d


def local_orbit(a: int, k: int, p: int, e: int) -> tuple[int, int]:
    if k == 1:
        return 0, 1
    modulus = p**e
    a %= modulus
    if a % p == 0:
        if a == 0:
            return 0, 1
        v, x = 0, a
        while x % p == 0:
            v, x = v+1, x//p
        t = 0
        while v < e:
            v, t = v*k, t+1
        return t, 1
    d = order(a, modulus)
    co, t, b = d, 0, 1
    while gcd(co, k) != 1:
        co //= gcd(co, k)
    parallel = d//co
    while b % parallel:
        b, t = b*k, t+1
    return t, order(k, co)


def verify() -> dict:
    units = [a for a in range(360) if gcd(a, 360) == 1]
    with tempfile.TemporaryDirectory() as directory:
        dest = Path(directory)
        subprocess.run([sys.executable, str(ROOT/'exact/generate_power_atlas.py'),
                        '--export', str(dest)], check=True, stdout=subprocess.DEVNULL)
        names = ['maps.csv','summary.csv','composition.csv','prime-power-witnesses.csv','prime-powers.csv']
        for name in names:
            require((OUT/name).read_bytes() == (dest/name).read_bytes(), f'generated bytes: {name}')
        expanded = (dest/'expanded-atlas.json').read_bytes()
        full = json.loads(expanded)
    require(full['modulus'] == 360 and full['positive_exponent_representatives'] == list(range(1,15)), 'scope')
    require(full['prime_power_bound'] == 1_000_000, 'prime-power scope')
    require(full['node_columns'] == ['r','tail','period','first_cycle_vertex','cycle_minimum'], 'node schema')
    require(len(full['maps']) == 14, 'map count')
    maps = [[crt_power(a, k) for a in range(360)] for k in range(1, 15)]
    require(csv_rows((OUT/'maps.csv').read_bytes()) == [[a]+[f[a] for f in maps] for a in range(360)], 'CRT maps')
    summaries = []
    for k, (f, stored) in enumerate(zip(maps, full['maps']), 1):
        rows = [floyd(f, a) for a in range(360)]
        for a, row in enumerate(rows):
            local = [local_orbit(a,k,p,e) for p,e in ((2,3),(3,2),(5,1))]
            require(row[1:3] == [max(t for t,_ in local), lcm(*(v for _,v in local))], 'local orbit formula')
            require(row[1] <= 2 and row[2] <= 2, 'universal orbit bound')
            require(f[f[f[f[a]]]] == f[f[a]], 'f^4 = f^2')
        cycles = []
        for a, mu, period, entry, minimum in rows:
            if mu == 0 and a == minimum:
                cy = [a]
                for _ in range(period-1):
                    cy.append(f[cy[-1]])
                cycles.append(cy)
        fibers = [[a for a in range(360) if f[a] == b] for b in range(360)]
        uf = Counter(f[a] for a in units)
        require(len(set(uf.values())) == 1, 'unit fiber uniformity')
        summary = [k,len(set(f)),len(uf),96//len(uf),sum(f[a]==a for a in range(360)),
                   sum(len(c)==2 for c in cycles),sum(len(c) for c in cycles),max(r[1] for r in rows)]
        summary += [sum(r[1]==t for r in rows) for t in range(3)] + [sum(f[a]==a for a in units)]
        expected = {'k':k,'successors':f,'fibers':fibers,'nodes':rows,'cycles':cycles,
                    'summary':summary,'fiber_size_histogram':[list(v) for v in sorted(Counter(map(len,fibers)).items())]}
        require(stored == expected, f'complete graph k={k}')
        summaries.append(summary)
    require(csv_rows((OUT/'summary.csv').read_bytes()) == summaries, 'summary table')
    require(len({tuple(f) for f in maps}) == 14, 'distinct maps')
    require(len({(s[1],s[4]) for s in summaries}) == 14, 'distinct unlabeled graph invariants')
    require(len({tuple(f[a] for a in units) for f in maps}) == 12, 'unit map types')
    require(len({(s[2],s[11]) for s in summaries}) == 12, 'unit graph types')
    require([a for a in range(360) if maps[1][a] != maps[13][a]] == list(range(2,360,4)), '90 square exceptions')
    for a in range(360):
        r = maps[12][a]
        nil = (a-r) % 360
        require(r*nil % 360 == 0 and nil**3 % 360 == 0, 'regular/nilpotent split')
        require((maps[1][a]-maps[13][a]) % 360 == (180 if a%4==2 else 0), 'nilpotent-square correction')
        require(all(maps[k-1][a] == maps[k-1][r] for k in range(3,15)), 'stable factorization through skeleton')
    comp = csv_rows((OUT/'composition.csv').read_bytes())
    for i in range(1, 15):
        require(comp[i-1][0] == i, 'composition row label')
        for j in range(1, 15):
            q = comp[i-1][j]
            require(1 <= q <= 14, 'composition representative')
            require(maps[q-1] == [maps[i-1][maps[j-1][a]] for a in range(360)], 'composition')
            require(q == (i*j if i*j <= 2 else 3+(i*j-3)%12), 'exponent normalization')
    idempotents = [k for k in range(1,15) if comp[k-1][k] == k]
    require(idempotents == [1,4,9,12,13], 'idempotent maps')
    require([pow(2,k,8) for k in (1,13,2,14)] == [2,0,4,0], 'exception witnesses')
    require(order(7,360) == 12, 'minimal period witness')
    # A new, independent trial-division prime list; no sieve/SPF imports.
    X = 1_000_000
    ps = [p for p in range(2,isqrt(X)+1) if all(p%d for d in range(2,isqrt(p)+1))]
    witnesses, power_rows, pushforward_cells = [], [], 0
    for e in range(2,20):
        selected = [p for p in ps if p**e <= X]
        actual = Counter(p**e % 360 for p in selected)
        base_counts = Counter(p%360 for p in selected)
        predicted = [sum(base_counts[a] for a in range(360) if crt_power(a,e)==r) for r in range(360)]
        require(predicted == [actual[r] for r in range(360)], f'prime-power pushforward e={e}')
        pushforward_cells += 360
        q = e if e<=2 else 3+(e-3)%12
        power_rows.append([e,q,len(selected),sum(p>5 for p in selected)])
        witnesses += [[p**e,p,e,p**e%360] for p in selected]
    require(2**20 > X and len(witnesses) == len({v[0] for v in witnesses}) == 236, 'power completeness/uniqueness')
    require(csv_rows((OUT/'prime-power-witnesses.csv').read_bytes()) == sorted(witnesses), 'prime-power witnesses')
    require(csv_rows((OUT/'prime-powers.csv').read_bytes()) == power_rows, 'prime-power totals')
    paths = [ROOT/'exact'/n for n in ('generate_power_atlas.py','verify_power_atlas.py')]
    paths += [OUT/n for n in names]
    return {'schema':'mod360-power-atlas-certificate-v1','status':'PASS','modulus':360,
            'checks':{'maps':14,'vertex_records':5040,'composition_vertex_checks':70560,
                      'different_graphs_by_image_and_fixed_count':14,'unit_graph_types':12,
                      'nilpotent_square_exception_count':90,
                      'prime_power_bound':X,'proper_prime_power_witnesses':236,
                      'prime_power_pushforward_cells':pushforward_cells},
            'idempotent_map_representatives':idempotents,'external_independent_review':False,
            'sha256':{str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest() for p in paths},
            'expanded_atlas_sha256':hashlib.sha256(expanded).hexdigest()}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument('--check',action='store_true')
    group.add_argument('--write',action='store_true')
    args = parser.parse_args()
    result = verify()
    content = (json.dumps(result,sort_keys=True,indent=2)+'\n').encode()
    if args.write:
        CERT.parent.mkdir(parents=True,exist_ok=True)
        CERT.write_bytes(content)
    else:
        require(CERT.is_file() and CERT.read_bytes()==content,'certificate mismatch')
    print(json.dumps(result,sort_keys=True,indent=2))


if __name__ == '__main__':
    main()
